name: Go

on:
  push:
    branches: [ main ]
    tags: [ '[0-9]+.[0-9]+.[0-9]+']
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: 'Build and Release'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Test
      run: go test -v ./...
    - name: Build
      run: go build -o bin/extensions/papertrail-lambda-extension main.go
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      if: startsWith(github.ref, 'refs/tags/')
      with:
        type: 'zip'
        filename: 'papertrail-lambda-extension-${{ steps.get_version.outputs.VERSION }}.zip'
        path: '**'
        directory: 'bin'
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: CHANGES.md
        files: |
          bin/papertrail-lambda-extension-${{ steps.get_version.outputs.VERSION }}.zip

